apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helpnow

resources:
  - cluster.yaml
  - service.yaml

secretGenerator:
  - name: helpnow-postgres-creds
    envs:
      - .env

configMapGenerator:
  - name: helpnow-init-sql
    files:
      - schema.sql

generatorOptions:
  disableNameSuffixHash: true
