apiVersion: v1
kind: Service
metadata:
  name: helpnow-postgres-lb
  # Namespace handled by Kustomize
spec:
  type: LoadBalancer
  ports:
    - port: 5555
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    cnpg.io/cluster: helpnow-postgres
    role: primary
