apiVersion: v1
kind: Service
metadata:
  name: clickhouse-metrics-lb
  namespace: helpnow
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8124
      targetPort: 8123
    - name: tcp
      port: 9001
      targetPort: 9000
  selector:
    app: clickhouse
